---
title: "Coverage UTRs Overview"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, echo=F , include=F}
knitr::opts_chunk$set(echo = TRUE)
source("../code/utils.R")
load_R_essentials()
library(rtracklayer)
```

First we should read in the resulting data:

```{r read}
# function to read in the data
read_utrs <- function(file, input_strain) {
  df <- as.data.frame(import.gff3(file)) %>%
    select(Parent,type,width)
  df$strain <- input_strain
  df$Parent <- as.character(df$Parent)
  return(df)
}

utrs3d7 <- read_utrs("../data/longest_utrs_3d7_plasmodb_compatible.gff", "3D7")
utrshb3 <- read_utrs("../data/longest_utrs_hb3_plasmodb_compatible.gff", "HB3")
utrsit <- read_utrs("../data/longest_utrs_it_plasmodb_compatible.gff", "IT4")
utrs <- rbind(utrs3d7,utrshb3,utrsit)
```

## 5' UTRs

What does the distribution of 5' UTRs look like?

```{r 5utrs-hist}
utrs %>% 
  filter(type == "5UTR") %>% 
  ggplot(aes(x=width)) + 
  geom_histogram(color="grey90",bins=30) + 
  facet_grid(.~strain) +
  theme(axis.text.x = element_text(angle = 55, hjust = 1))
```

```{r 5utrs-boxplots}
utrs %>% 
  filter(type == "5UTR") %>% 
  ggplot(aes(x=strain,y=width)) + 
  geom_boxplot(fill="grey70")
```

How do summary statistics vary between strains?

```{r 5utrs-summary}
utrs %>% 
  filter(type == "5UTR") %>% 
  group_by(strain) %>% 
  summarise(mean=mean(width),median=median(width),sd=sd(width))
```

## 3' UTRs

What does the distribution of 3' UTRs look like?

```{r 3utrs-hist}
utrs %>% 
  filter(type == "3UTR") %>% 
  ggplot(aes(x=width)) + 
  geom_histogram(color="grey90",bins=30) + 
  facet_grid(.~strain) + 
  theme(axis.text.x = element_text(angle = 55, hjust = 1))
```

```{r 3utrs-boxplots}
utrs %>% 
  filter(type == "3UTR") %>% 
  ggplot(aes(x=strain,y=width)) + 
  geom_boxplot(fill="grey70")
```

How do summary statistics vary between strains?

```{r 3utrs-summary}
utrs %>% 
  filter(type == "3UTR") %>% 
  group_by(strain) %>% 
  summarise(mean=mean(width),median=median(width),sd=sd(width))
```
## Homopolymer tracts

NEED TO ADD THIS.
